import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import products from "../products.json";
import { initiateCheckout } from "../lib/payments";

const defaultCart = {
  products: {}, //easier to icompare one object to another than with arrays
};

export default function Home() {
  const [cart, updateCart] = useState(defaultCart);

  console.log("cart", cart);

  function addToCart({ id } = {}) {
    updateCart((prev) => {
      let cartState = { ...prev }; //create copy of prev state

      if (cartState.products[id]) {
        console.log("product with id already in cart: ", id);
        cartState.products[id].quantity = cartState.products[id].quantity + 1;
      } else {
        console.log("product with id not yet in cart: ", id);
        cartState.products[id] = {
          id,
          quantity: 1,
        };
      }

      return cartState;
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Space Jelly Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Space Jelly Shop</h1>

        <p className={styles.description}>
          The best space jellyfish swag on the web!
        </p>

        <p className={styles.description}>
          <strong>Items: 2</strong>
          <br />
          <strong>Total Cost: £16</strong>
          <br />
          <button className={styles.button}>Check Out</button>
        </p>

        <ul className={styles.grid}>
          {products.map((product) => {
            const { id, image, title, description, price } = product;
            return (
              <li key={id} className={styles.card}>
                <a href="https://nextjs.org/docs">
                  <Image
                    layout="responsive"
                    width={1600}
                    height={1200}
                    src={image}
                    alt={title}
                  />
                  <h3>{title}</h3>
                  <p>£{price}</p>
                  <p>{description}</p>
                </a>
                <p>
                  <button
                    className={styles.button}
                    onClick={
                      () =>
                        addToCart({
                          id,
                        })
                      /* initiateCheckout({
                        lineItems: [
                          {
                            price: id,
                            quantity: 1,
                          },
                        ],
                      }) */
                    }
                  >
                    Buy Now!
                  </button>
                </p>
              </li>
            );
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
